namespace: yum_unit_test_migration_spec
name: yum_collection
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  amazon.amazon: '>=1.0'
repository: git@github.com:coll-test/yum_unit_test_migration_spec.yum_collection.git
documentation: https://github.com/coll-test/yum_unit_test_migration_spec.yum_collection/tree/master/docs
homepage: https://github.com/coll-test/yum_unit_test_migration_spec.yum_collection
issues: https://github.com/coll-test/yum_unit_test_migration_spec.yum_collection/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
